//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSoftwareWebService.DataSloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupe_ogranicenja
    {
        public int Id_grupe_ogranicenja { get; set; }
        public int id_tip_opreme1 { get; set; }
        public int id_parametra1 { get; set; }
        public Nullable<int> id_tip_opreme2 { get; set; }
        public Nullable<int> id_parametra2 { get; set; }
        public string tipProvere { get; set; }
        public int id_tip_opreme_kolekcije { get; set; }
    }
}
