//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSoftwareWebService.DataSloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class istorija_kupovine_oprema
    {
        public int id_oprema { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<double> cena_opreme_kad_je_prodata { get; set; }
        public Nullable<double> popust_na_cenu { get; set; }
        public Nullable<int> ukupna_cena_artikla { get; set; }
        public int id_istorija_kupovine { get; set; }
    
        public virtual oprema oprema { get; set; }
    }
}
