//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSoftwareWebService.DataSloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class konfiguracija_kolekcije
    {
        public int Id_tip_opreme_kolekcije { get; set; }
        public int id_tip_opreme_deo_kolekcije { get; set; }
        public int redosled_prikazivanja { get; set; }
        public int moguca_kolicina_unosa { get; set; }
    }
}
