//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSoftwareWebService.DataSloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class oblasti_opreme
    {
        public oblasti_opreme()
        {
            this.tip_opreme = new HashSet<tip_opreme>();
        }
    
        public int id_oblasti_opreme { get; set; }
        public string naziv_oblasti_opreme { get; set; }
        public string picture { get; set; }
        public bool deletedField { get; set; }
    
        public virtual ICollection<tip_opreme> tip_opreme { get; set; }
    }
}
