//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSoftwareWebService.DataSloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class oprema
    {
        public oprema()
        {
            this.istorija_kupovine_oprema = new HashSet<istorija_kupovine_oprema>();
            this.narudzbines = new HashSet<narudzbine>();
            this.parametarOpremas = new HashSet<parametarOprema>();
        }
    
        public int id_oprema { get; set; }
        public string proizvodjac { get; set; }
        public string naslov { get; set; }
        public double cena { get; set; }
        public string opis { get; set; }
        public string model { get; set; }
        public int id_tip_opreme { get; set; }
        public Nullable<bool> lager { get; set; }
        public Nullable<int> kolicina_u_rezervi { get; set; }
        public Nullable<int> kolicina_na_lageru { get; set; }
        public Nullable<int> oprema_na_popustu { get; set; }
        public string slika { get; set; }
        public bool deletedField { get; set; }
    
        public virtual ICollection<istorija_kupovine_oprema> istorija_kupovine_oprema { get; set; }
        public virtual ICollection<narudzbine> narudzbines { get; set; }
        public virtual ICollection<parametarOprema> parametarOpremas { get; set; }
    }
}
