//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSoftwareWebService.DataSloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametri
    {
        public parametri()
        {
            this.parametarOpremas = new HashSet<parametarOprema>();
        }
    
        public int id_parametri { get; set; }
        public string naziv_parametra { get; set; }
        public string default_vrednost { get; set; }
        public int id_tip_opreme { get; set; }
        public bool za_filter { get; set; }
        public string tipParametra { get; set; }
        public bool deletedField { get; set; }
    
        public virtual ICollection<parametarOprema> parametarOpremas { get; set; }
        public virtual tip_opreme tip_opreme { get; set; }
    }
}
