//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSoftwareWebService.DataSloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezervacije
    {
        public int id_rezervacije { get; set; }
        public string ime { get; set; }
        public Nullable<System.DateTime> datum_rezervacije { get; set; }
        public Nullable<System.DateTime> datum_isteka_rezervacije { get; set; }
        public Nullable<System.DateTime> datum_azuriranja_rezervacije { get; set; }
        public string broj_telefona { get; set; }
    }
}
